name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install xml
      run: sudo apt-get install libxml2-dev libxml2-doc
    - name: install pcre
      run: sudo apt-get install libpcre2-dev
    - name: configure
      run: ./configure
    - name: client_app
      run: ./app/build/ytk_client_app xml/network_device.xml
